import type { HookTemplate, HookType } from "./types";

export const HOOK_TEMPLATES: Record<HookType, HookTemplate> = {
  pattern_interrupt: {
    key: "pattern_interrupt",
    name: "Pattern Interrupt",
    hookType: "pattern_interrupt",
    visualSetup: "Unexpected jarring visual that breaks the scroll",
    cameraAction: "Sudden snap zoom, aggressive push-in",
    subjectAction: "Unexpected action or expression that surprises the viewer",
    emotionTone: "shocking, surprising, disruptive",
    promptPrefix: "scroll-stopping unexpected visual, immediate attention-grab, jarring pattern interrupt, viewer frozen mid-scroll, ",
    motionCue: "sudden snap zoom in, aggressive push-in",
    durationHint: "1-2 seconds",
    description: "Breaks viewer's scrolling pattern with a jarring unexpected visual",
  },
  bold_claim: {
    key: "bold_claim",
    name: "Bold Claim",
    hookType: "bold_claim",
    visualSetup: "Character looking directly into lens with absolute certainty",
    cameraAction: "Slow confident push-in",
    subjectAction: "Direct intense eye contact, slight forward lean toward camera",
    emotionTone: "confident, authoritative, unshakeable",
    promptPrefix: "intense direct eye contact into lens, commanding authority presence, absolute self-certainty, zero doubt expression, ",
    motionCue: "slow deliberate push-in, authority framing",
    durationHint: "1-3 seconds",
    description: "Character delivers a bold statement directly to camera with zero hesitation",
  },
  curiosity_hook: {
    key: "curiosity_hook",
    name: "Curiosity Hook",
    hookType: "curiosity",
    visualSetup: "Something partially revealed — viewer must know what happens next",
    cameraAction: "Slow reveal pan or anticipation tilt",
    subjectAction: "Knowing look, slight smirk, something off-frame grabbing their attention",
    emotionTone: "mysterious, intriguing, tantalizing",
    promptPrefix: "tantalizing partial reveal, curiosity-gap visual, viewer must know more, mysterious knowing expression, ",
    motionCue: "slow reveal pan, anticipation tilt toward mystery",
    durationHint: "2-3 seconds",
    description: "Creates a curiosity gap that psychologically compels continued watching",
  },
  pov_hook: {
    key: "pov_hook",
    name: "POV Hook",
    hookType: "pov",
    visualSetup: "First-person perspective — the viewer is inside the scene",
    cameraAction: "Slight handheld drift, immersive movement",
    subjectAction: "Character reacts directly to the viewer/camera",
    emotionTone: "immersive, direct, engaging, intimate",
    promptPrefix: "immersive first-person POV, viewer placed inside the scene, direct address to camera, you-are-there perspective, ",
    motionCue: "handheld immersive drift, subtle POV shake",
    durationHint: "2-3 seconds",
    description: "Places the viewer directly inside the scene as a participant",
  },
  transformation_hook: {
    key: "transformation_hook",
    name: "Transformation Hook",
    hookType: "transformation",
    visualSetup: "Show the impressive result/after state first",
    cameraAction: "Dramatic reveal push-in or crane up",
    subjectAction: "Confident display of transformation result, proud reveal",
    emotionTone: "impressed, desiring, aspiring",
    promptPrefix: "dramatic reveal of impressive result, aspirational outcome displayed, desire-inducing transformation, show the prize first, ",
    motionCue: "dramatic crane up reveal, cinematic push-in",
    durationHint: "2-3 seconds",
    description: "Leads with the result to create desire and curiosity about the how",
  },
  social_proof_hook: {
    key: "social_proof_hook",
    name: "Social Proof Hook",
    hookType: "social_proof",
    visualSetup: "Authentic evidence of real results, testimonial energy",
    cameraAction: "Warm approachable push-in",
    subjectAction: "Genuine excited smile, sharing news they can't contain",
    emotionTone: "excited, validated, authentic",
    promptPrefix: "genuine excitement sharing real results, authentic testimonial energy, real person real outcome expression, can't-believe-it happened face, ",
    motionCue: "warm approachable push-in, friend-sharing intimacy",
    durationHint: "1-2 seconds",
    description: "Establishes credibility through authentic social proof energy",
  },
  question_hook: {
    key: "question_hook",
    name: "Question Hook",
    hookType: "question",
    visualSetup: "Character posing a question the audience deeply identifies with",
    cameraAction: "Gentle drift toward camera, intimate pull-in",
    subjectAction: "Questioning expression, engaged curious look, slight head tilt",
    emotionTone: "curious, relatable, conspiratorial",
    promptPrefix: "engaging questioning expression, relatable curiosity energy, viewer recognition face — they feel seen, slight knowing head tilt, ",
    motionCue: "gentle drift toward lens, intimate questioning pull-in",
    durationHint: "1-2 seconds",
    description: "Opens with a question the audience deeply identifies with",
  },
  silent_stare: {
    key: "silent_stare",
    name: "Silent Stare",
    hookType: "pattern_interrupt",
    visualSetup: "Character stands perfectly still in rain-soaked street, staring into lens",
    cameraAction: "Ultra-slow push-in from wide to close, creeping in",
    subjectAction: "Absolute stillness, cold unblinking stare into lens",
    emotionTone: "cold, intense, unnerving, magnetic",
    promptPrefix: "absolute stillness in rain, cold unblinking stare into lens, magnetic intensity, you cannot look away, silent protagonist energy, rain falling around motionless figure, ",
    motionCue: "ultra-slow creeping push-in, almost imperceptible drift",
    durationHint: "2-4 seconds",
    description: "Character 28 signature: silent unblinking stare in rain — can't look away",
  },
  urban_reveal: {
    key: "urban_reveal",
    name: "Urban Reveal",
    hookType: "transformation",
    visualSetup: "Slow crane up from wet cobblestones to reveal character centered in street",
    cameraAction: "Slow crane up from ground level, full body reveal",
    subjectAction: "Standing centered, hands relaxed, facing camera with composed intensity",
    emotionTone: "cinematic, powerful, presence-establishing",
    promptPrefix: "cinematic full-body reveal, slow crane up from wet cobblestones, lone figure centered in rain-soaked street, establishing shot power, blue hour moody atmosphere, ",
    motionCue: "slow crane up from ground to eye level, full reveal",
    durationHint: "3-5 seconds",
    description: "Character 28 signature: cinematic crane-up reveal on wet empty street",
  },
  neon_emergence: {
    key: "neon_emergence",
    name: "Neon Emergence",
    hookType: "pattern_interrupt",
    visualSetup: "Character's face emerges from darkness into neon-lit alley",
    cameraAction: "Slow push-in from dark to neon-lit face",
    subjectAction: "Face emerges from shadow, eyes catching neon light",
    emotionTone: "dramatic, mysterious, cinematic",
    promptPrefix: "face emerging from urban darkness into neon light, atmospheric steam swirling, cyberpunk color spill, dramatic emergence from shadow, cinematic reveal, ",
    motionCue: "slow push-in from darkness, neon light reveal",
    durationHint: "2-4 seconds",
    description: "Character 28 variant: dramatic neon emergence from urban shadow",
  },
};

export function getHook(key: HookType): HookTemplate | undefined {
  return HOOK_TEMPLATES[key];
}

export function listHooks(): HookTemplate[] {
  return Object.values(HOOK_TEMPLATES);
}
